[package]
name = "opengov-submit"
version = "0.1.0"
edition = "2021"
authors = ["joepetrowski"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
parity-scale-codec = "3.2.1"
subxt = "0.25.0"
hex = "0.4.3"
